:green_heart: (test report) Test report WIP

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,4 +32,10 @@ jobs:
     - name: Install Playwright
       run: npx playwright install
     - name: Run Playwright tests
-      run: npx playwright test --browser=firefox --config=prod.config.ts --workers=${{ github.event.inputs.workersAmount }} --grep=${{ github.event.inputs.tags }}
+      run: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test --browser=firefox --config=prod.config.ts --workers=${{ github.event.inputs.workersAmount }} --grep=${{ github.event.inputs.tags }} --reporter=junit
+    - uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: JEST Tests            # Name of the check run which will be created
+        path: results.xml    # Path to test results
+        reporter: jest-junit        # Format of test results
